# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Xshop_web_CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
            max-parallel: 4
            matrix:
                python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      uses: Gr1N/setup-poetry@v3
      run: poetry --version
        env:
          POETRY_VIRTUALENVS_PATH: ~/.cache/pypoetry
          POETRY_HTTP_BASIC_MY_REPOSITORY_PASSWORD: secret
    - name: Run Tests
      run: |
        python manage.py test
