name: Xshop_web_CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
            max-parallel: 4
            matrix:
                python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: Gr1N/setup-poetry@v3
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pypoetry/virtualenvs
        key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
    - name: Get poetry version
      run: poetry --version
    - name: Install dependencies
      run: poetry install
    - name: Run Tests
      run: poetry run python manage.py test
    - name: Run flake8 linter based on black
      run: poetry run flake8
