# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Xshop_web_CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
            max-parallel: 4
            matrix:
                python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Poetry
      uses: Gr1N/setup-poetry@v3
    # - uses: actions/cache@v1
    #   with:
    #     path: ~/.cache/pypoetry/virtualenvs
    #     key: ${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}
    #     restore-keys: |
    #       ${{ runner.os }}-poetry-
    - name: Get poetry version
      run: poetry --version
    - name: Install dependencies
      run: poetry install && poerty shell
    # - name: Install pipenv 
    #   run: pipenv install -r requirements.txt
    # - name: run pipenv
    #   run: pipenv shell
    - name: Run Tests
      run: |
        python manage.py test
